version: "3"

services:
  velyb-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: velyb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: velyb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  velyb-web-server:
    build:
      context: .
      dockerfile: apps/velyb-web-server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8000

  microservices_authentification:
    build:
      context: .
      dockerfile: apps/microservices/authentification/Dockerfile
    ports:
      - "8001:8001"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8001

  microservices_favorite:
    build:
      context: .
      dockerfile: apps/microservices/favorite/Dockerfile
    ports:
      - "8002:8002"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8002

  microservices_user:
    build:
      context: .
      dockerfile: apps/microservices/user/Dockerfile
    ports:
      - "8003:8003"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8003

  api-caching-server:
    build:
      context: .
      dockerfile: apps/api-caching-server/Dockerfile
    ports:
      - "8004:8004"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8004
volumes:
  mysql_data:
